/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  theme: {
    extend: {
      colors: {
        "outline-variant": "#c5c6cd",
        "tertiary-fixed": "#6ffbbe",
        "surface-container-low": "#eff4ff",
        "primary-container": "#1e293b",
        "secondary-fixed-dim": "#adc6ff",
        "surface-container-lowest": "#ffffff",
        "surface-bright": "#f8f9ff",
        "on-tertiary-container": "#00a472",
        "secondary-container": "#2170e4",
        "on-background": "#0b1c30",
        "primary-fixed-dim": "#bcc7de",
        "secondary-fixed": "#d8e2ff",
        "surface-container-highest": "#d3e4fe",
        "secondary": "#0058be",
        "on-secondary-fixed-variant": "#004395",
        "surface-dim": "#cbdbf5",
        "primary-fixed": "#d8e3fb",
        "on-primary-fixed-variant": "#3c475a",
        "surface-tint": "#545f73",
        "inverse-surface": "#213145",
        "on-secondary-container": "#fefcff",
        "surface-container-high": "#dce9ff",
        "on-surface": "#0b1c30",
        "surface-container": "#e5eeff",
        "outline": "#75777d",
        "on-primary": "#ffffff",
        "on-surface-variant": "#45474c",
        "background": "#f8f9ff",
        "primary": "#091426",
        "inverse-on-surface": "#eaf1ff",
        "surface-variant": "#d3e4fe",
        "surface": "#f8f9ff",
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Plus Jakarta Sans", "sans-serif"],
      },
    },
  },
  plugins: [],
};
